---
title: "National Football League NFC Stadiums" 
output:
  html_document:
    keep_md: yes
  fig_caption: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## July 15, 2017
### Click on Team Logos for Team Name, Stadium and Link 

```{r, echo=FALSE}
setwd("~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project")
library(leaflet)

cardinals <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/cardinals.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

niners <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/niners.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16) 

seahawks <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/seahawks.png",
  iconWidth = 45, iconHeight = 28,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16) 

rams <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/rams.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16) 

packers <-  makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/packers.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16) 
  
lions <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/lions.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)
  
vikings <-  makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/vikings.png",
  iconWidth = 45, iconHeight = 45,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16) 
  
bears <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/bears.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

cowboys <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/cowboys.png",
  iconWidth = 42, iconHeight = 42,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

eagles <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/eagles.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

redskins <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/redskins.png",
  iconWidth = 40, iconHeight = 40,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

giants <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/giants.png",
  iconWidth = 35, iconHeight = 35,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

panthers <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/panthers.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

saints <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/saints.png",
  iconWidth = 42, iconHeight = 42,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

falcons <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/falcons.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

buccaneers <- makeIcon(
  iconUrl = "~/Telematics and Analytics/Statistics/Data Science Specialization/Data Products/week2/project/buccaneers.png",
  iconWidth = 45, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16)

teams <- iconList(cardinals, niners, seahawks, rams, 
                  packers, lions, vikings, bears,
                  cowboys, eagles, redskins, giants, 
                  panthers, saints, falcons, buccaneers) 

teamLatLong <- data.frame(
  lat = c(33.5276247, 37.4032235, 47.5951554, 34.014057, 44.5014315, 42.3400215, 44.9741579, 41.8624094,
          32.7472889, 39.9007715, 38.9076468, 40.8139441, 35.2258156, 29.9510656, 33.7576941, 27.9758738),
  lng = c(-112.264748, -121.9720247, -122.3338281, -118.2900641, -88.061846, -83.0465039, -93.2598886, -87.6181376,
          -97.0966826, -75.1696522, -76.8667351, -74.0746427, -80.8550322, -90.0834329, -84.4030172, -82.5055231))

teamSites <- c(
  "<a href='https://www.google.com/maps/place/University+of+Phoenix+Stadium/@33.5276247,-112.264748,945m/data=!3m2!1e3!5s0x872b404828c7c8d3:0x7878fa75abac5570!4m8!1m2!2m1!1suniversity+of+phoenix+stadium,+Phoenix+Metropolitan+Area,+East+Veterans+Way,+Tempe,+AZ!3m4!1s0x872b40484caa40dd:0xb9c497aa9569305b!8m2!3d33.5276247!4d-112.2625593'>Arizona Cardinals, Univ. of Phoenix Stadium</a>",
  "<a href='https://www.google.com/maps/place/4900+Marie+P+DeBartolo+Way,+Santa+Clara,+CA+95054/@37.4031582,-121.9720244,854m/data=!3m2!1e3!4b1!4m5!3m4!1s0x808fc9b7df7b689d:0x6750c96539e523ab!8m2!3d37.403154!4d-121.9698357'>San Francisco 49ers, Levis Stadium</a>",
  "<a href='https://www.google.com/maps/place/CenturyLink+Field/@47.5951554,-122.3338281,725m/data=!3m2!1e3!4b1!4m5!3m4!1s0x54906aa3b9f1182b:0xa636cd513bba22dc!8m2!3d47.5951518!4d-122.3316394'>Seattle Seahawks, CenturyLink Field</a>",
  "<a href='https://www.google.com/maps/place/LA+Memorial+Coliseum/@34.014057,-118.2900641,891m/data=!3m3!1e3!4b1!5s0x80c2c80878693a29:0xad0170a7ce1f864c!4m5!3m4!1s0x80c2c807d74e67fb:0x54cf0a70d5943d36!8m2!3d34.0140526!4d-118.2878754'>Los Angeles Rams, LA Memorial Coliseum</a>", 
  
  "<a href='https://www.google.com/maps/place/Lambeau+Field/@44.5014315,-88.061846,574m/data=!3m1!1e3!4m5!3m4!1s0x8802fa51d9541b0f:0x45828001c843dcdd!8m2!3d44.5013406!4d-88.0622083'>Green Bay Packers, Lambeau Field</a>",
  "<a href='https://www.google.com/maps/place/Ford+Field/@42.3400215,-83.0465039,483m/data=!3m1!1e3!4m5!3m4!1s0x883b2d2d6742e0b7:0xd4923792afe689b6!8m2!3d42.3400064!4d-83.045603'>Detroit Lions, Ford Field</a>",
  "<a href='https://www.google.com/maps/place/U.S.+Bank+Stadium+Station/@44.9741579,-93.2598886,801m/data=!3m1!1e3!4m5!3m4!1s0x52b32d61ceb40a19:0xdf80a8338d4a4196!8m2!3d44.975079!4d-93.259743'>Minnesota Vikings, U.S. Bank Stadium</a>",
  "<a href='https://www.google.com/maps/place/Soldier+Field/@41.8624094,-87.6181376,592m/data=!3m2!1e3!5s0x880e2b7daf0129ef:0xb80465bc178e5289!4m5!3m4!1s0x880e2b7db595e7bb:0xa3c99cebaff8029c!8m2!3d41.8623132!4d-87.6166884'>Chicago Bears, Soldier Field</a>",

  "<a href='https://www.google.com/maps/place/AT%26T+Stadium/@32.7472889,-97.0966826,904m/data=!3m2!1e3!4b1!4m5!3m4!1s0x864e7d86c8884727:0x6d1e60e88c6a9df8!8m2!3d32.7472844!4d-97.0944939'>Dallas Cowboys, AT&T Stadium</a>",
  "<a href='https://www.google.com/maps/place/Lincoln+Financial+Field/@39.9007715,-75.1696522,825m/data=!3m2!1e3!4b1!4m5!3m4!1s0x89c6c5ed6a50daaf:0xe01f1b45e49fbe99!8m2!3d39.9007674!4d-75.1674635'>Philadelphia Eagles, Lincoln Finanical Field</a>",
  "<a href='https://www.google.com/maps/place/FedExField/@38.9076468,-76.8667351,836m/data=!3m2!1e3!4b1!4m5!3m4!1s0x89b7bf8767ad5c43:0x4770659d01cbb79e!8m2!3d38.9076426!4d-76.8645464'>Washington Redskins, FedEx Field</a>",
  "<a href='https://www.google.com/maps/place/MetLife+Stadium+Dr,+East+Rutherford,+NJ+07073/@40.8139441,-74.0746427,814m/data=!3m2!1e3!4b1!4m5!3m4!1s0x89c2f87c67ba7dcd:0xe7325b1ff58a02b9!8m2!3d40.8139401!4d-74.072454'>New York Giants, MetLife Stadium</a>",
  
  "<a href='https://www.google.com/maps/place/Bank+of+America+Stadium/@35.2258156,-80.8550322,878m/data=!3m2!1e3!4b1!4m5!3m4!1s0x8856a02cbdb65535:0x480ec8bd36ab934f!8m2!3d35.2257952!4d-80.8528415'>Carolina Panthers, Bank of America Stadium</a>",
  "<a href='https://www.google.com/maps/place/Mercedes-Benz+Superdome/@29.9510656,-90.0834329,931m/data=!3m2!1e3!4b1!4m5!3m4!1s0x8620a5dd82214811:0x6e354b4a1659e3af!8m2!3d29.951061!4d-90.0812442'>New Orleans Saints, Mercedes-Benz Superdome</a>",
  "<a href='https://www.google.com/maps/place/Georgia+Dome/@33.7576941,-84.4030172,894m/data=!3m2!1e3!4b1!4m5!3m4!1s0x88f5037e0b6542a3:0x157896307a1de070!8m2!3d33.7576897!4d-84.4008285'>Atlanta Falcons, Georgia Dome</a>",
  "<a href='https://www.google.com/maps/place/Raymond+James+Stadium/@27.9758738,-82.5055231,949m/data=!3m2!1e3!4b1!4m5!3m4!1s0x88c2c3b8dc9428cf:0xc1cd5337edfcf3df!8m2!3d27.9758691!4d-82.5033344'>Tampa Bay Buccaneers, Raymond James Stadium</a>"  
  )

map2 <- teamLatLong %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = teams, popup = teamSites)

map2

```